Separate vpn and other tunnels
Signed-off-by: Matt Barlow <matt.barlow@rackspace.com>

diff --git a/vpn/setup_tunnel b/vpn/setup_tunnel
--- a/vpn/setup_tunnel
+++ b/vpn/setup_tunnel
@@ -2,6 +2,14 @@
 
 set -e
 
+usage(){
+	echo "Usage: $0 gap_userid"
+	exit 1
+}
+
+# call usage() function if userid not supplied
+[[ $# -eq 0 ]] && usage
+
 chmod 400 config/id_rsa_jb config/pcf
 
 . .venv/bin/activate
@@ -9,13 +17,35 @@ chmod 400 config/id_rsa_jb config/pcf
 # enter local workstation password to update sudo timer
 sudo -v
 
-# clear dns cache, only on macs
-uname | grep Darwin && sudo killall -HUP mDNSResponder
+userid=${1}
 
-for i in 1 2 3; do
-  sshuttle --verbose --verbose --dns --remote=clubawa@inner 10.0.0.0/8 \
-    --ssh-cmd 'ssh -i config/pcf -F config/ssh_config' \
-    -x 10.240.1.0/24
-  echo "lost connection? will retry in 5 seconds"
-  sleep 5
-done
+if [ ${ENVIRONMENT_NAME} == "gap-cfpci-openstack" ]; then
+    echo "Connecting to ${ENVIRONMENT_NAME}"
+    sshuttle -D --verbose --dns --remote=${userid}@inner 10.107.0.0/16 \
+    --ssh-cmd 'ssh -F config/ssh_config' \
+    -x 10.240.1.0/24  \
+    -x 10.107.32.0/24 \
+    -x 10.107.40.0/21 \
+    -x 10.107.34.0/23 \
+    -x 10.107.36.0/23 \
+    -x 10.107.34.0/23
+    if [[ $? -eq 0 ]]; then
+        echo "Connected to ${ENVIRONMENT_NAME}"
+    else
+        echo "Failed to connect to ${ENVIRONMENT_NAME}"
+    fi
+else
+    echo "Connecting to ${ENVIRONMENT_NAME}"
+    sshuttle -D --verbose --verbose --dns --remote=${userid}@inner 10.0.0.0/8 \
+    --ssh-cmd 'ssh  -F config/ssh_config' \
+    -x 10.240.1.0/24  \
+    -x 10.107.48.0/24 \
+    -x 10.107.80.0/21 \
+    -x 10.107.50.0/23 \
+    -x 10.107.52.0/23 
+    if [[ $? -eq 0 ]]; then
+        echo "Connected to ${ENVIRONMENT_NAME}"
+    else
+        echo "Failed to connect to ${ENVIRONMENT_NAME}"
+    fi
+fi
