Daemonized sshuttle to PCI and Sandbox
Signed-off-by: BK Box <bk.box@rackspace.com>

diff --git a/vpn/setup_tunnel b/vpn/setup_tunnel
--- a/vpn/setup_tunnel
+++ b/vpn/setup_tunnel
@@ -7,8 +7,9 @@ usage(){
 	exit 1
 }
 
-# call usage() function if userid not supplied
 [[ $# -eq 0 ]] && usage
+
+userid=${1}
 
 chmod 400 config/id_rsa_jb config/pcf
 
@@ -17,35 +18,40 @@ chmod 400 config/id_rsa_jb config/pcf
 # enter local workstation password to update sudo timer
 sudo -v
 
-userid=${1}
+check_success(){
+    if [[ $? -eq 0 ]]; then
+        echo "Connected to ${1}"
+    else
+        echo "Failed to connect to ${1}"
+    fi
+}
 
-if [ ${ENVIRONMENT_NAME} == "gap-cfpci-openstack" ]; then
-    echo "Connecting to ${ENVIRONMENT_NAME}"
-    sshuttle -D --verbose --dns --remote=${userid}@inner 10.107.0.0/16 \
-    --ssh-cmd 'ssh -F config/ssh_config' \
-    -x 10.240.1.0/24  \
-    -x 10.107.32.0/24 \
-    -x 10.107.40.0/21 \
-    -x 10.107.34.0/23 \
-    -x 10.107.36.0/23 \
-    -x 10.107.34.0/23
-    if [[ $? -eq 0 ]]; then
-        echo "Connected to ${ENVIRONMENT_NAME}"
-    else
-        echo "Failed to connect to ${ENVIRONMENT_NAME}"
-    fi
+if curl -s -k --connect-timeout 5 https://10.107.48.22:25555 1>/dev/null; then
+    echo "Connected to PCI shuttle"
 else
-    echo "Connecting to ${ENVIRONMENT_NAME}"
-    sshuttle -D --verbose --verbose --dns --remote=${userid}@inner 10.0.0.0/8 \
-    --ssh-cmd 'ssh  -F config/ssh_config' \
-    -x 10.240.1.0/24  \
-    -x 10.107.48.0/24 \
-    -x 10.107.80.0/21 \
-    -x 10.107.50.0/23 \
-    -x 10.107.52.0/23 
-    if [[ $? -eq 0 ]]; then
-        echo "Connected to ${ENVIRONMENT_NAME}"
-    else
-        echo "Failed to connect to ${ENVIRONMENT_NAME}"
-    fi
+         echo "Connecting to PCI shuttle..."
+         sshuttle -D --pidfile /tmp/pci_shuttle.pid --dns --remote=${userid}@10.107.48.83 10.107.0.0/16 \
+         --ssh-cmd 'ssh -F config/ssh_config' \
+         -x 10.107.32.0/24 \
+         -x 10.107.40.0/21 \
+         -x 10.107.34.0/23 \
+         -x 10.107.36.0/23 \
+         -x 10.107.34.0/23
+         check_success "PCI Shuttle" 
+fi
+
+#sleep 5
+
+if curl -s -k --connect-timeout 5 https://10.2.16.21:25555 1>/dev/null; then
+    echo "Connected to general shuttle"
+else
+echo "Connecting to general shuttle..."
+         sshuttle -D --pidfile /tmp/general_shuttle.pid --dns --remote=${userid}@10.2.86.236 10.0.0.0/8 \
+         --ssh-cmd 'ssh -F config/ssh_config' \
+         -x 10.240.1.0/24  \
+         -x 10.107.48.0/24 \
+         -x 10.107.80.0/21 \
+         -x 10.107.50.0/23 \
+         -x 10.107.52.0/23 
+         check_success "General Shuttle"
 fi
